[package]
name = "cont_frac"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
workspace = "../../"
edition = "2018"

[dependencies]
num-integer = "0.1.46"
num-traits = "0.2.18"

[dependencies.integer]
path = "../integer"
