[package]
name = "iter"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
workspace = "../../"
edition = "2018"

[[bench]]
name = "bench"
harness = false

[dependencies]
bit-set = "0.5.3"

[dev-dependencies]
criterion = "0.3.6"
